CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL,
    role VARCHAR(32) NOT NULL,
    jury_field VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    quota INTEGER NOT NULL DEFAULT 0,
    base_score_requirement DOUBLE PRECISION NOT NULL DEFAULT 150
);

CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    tyt_score DOUBLE PRECISION,
    faculty VARCHAR(64),
    program_name VARCHAR(255),
    is_national BOOLEAN,
    is_disabled BOOLEAN,
    status VARCHAR(64),
    oysp_score DOUBLE PRECISION,
    final_placement_score DOUBLE PRECISION,
    average_score DOUBLE PRECISION,
    osym_doc_path VARCHAR(255),
    diploma_doc_path VARCHAR(255),
    health_doc_path VARCHAR(255),
    photo_doc_path VARCHAR(255),
    national_doc_path VARCHAR(255),
    disabled_doc_path VARCHAR(255),
    CONSTRAINT fk_application_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS jury_assignments (
    user_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, department_id),
    CONSTRAINT fk_assignment_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_assignment_department FOREIGN KEY (department_id) REFERENCES departments(id)
);

CREATE TABLE IF NOT EXISTS jury_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    jury_id BIGINT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    comment TEXT,
    timestamp TIMESTAMP,
    CONSTRAINT fk_score_application FOREIGN KEY (application_id) REFERENCES applications(id),
    CONSTRAINT fk_score_jury FOREIGN KEY (jury_id) REFERENCES users(id),
    CONSTRAINT uk_score_jury_application UNIQUE (jury_id, application_id)
);

CREATE INDEX IF NOT EXISTS idx_applications_user ON applications(user_id);
CREATE INDEX IF NOT EXISTS idx_applications_status ON applications(status);
CREATE INDEX IF NOT EXISTS idx_scores_application ON jury_scores(application_id);
