CREATE TABLE exam_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    session_type VARCHAR(32) NOT NULL,
    exam_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME,
    location VARCHAR(255),
    room VARCHAR(120),
    candidate_interval_minutes INTEGER,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_exam_session_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT chk_exam_session_type CHECK (session_type IN ('GROUP', 'INDIVIDUAL', 'TRACK'))
);

ALTER TABLE applications ADD COLUMN exam_session_id BIGINT;
ALTER TABLE applications ADD COLUMN exam_order INTEGER;
ALTER TABLE applications ADD COLUMN appointment_start_time TIME;
ALTER TABLE applications ADD COLUMN appointment_end_time TIME;
ALTER TABLE applications ADD CONSTRAINT fk_application_exam_session FOREIGN KEY (exam_session_id) REFERENCES exam_sessions(id);

CREATE INDEX idx_exam_sessions_department ON exam_sessions(department_id);
CREATE INDEX idx_applications_exam_session ON applications(exam_session_id);
