ALTER TABLE departments ADD COLUMN IF NOT EXISTS code VARCHAR(64);
ALTER TABLE departments ADD COLUMN IF NOT EXISTS exam_type VARCHAR(32) NOT NULL DEFAULT 'INDIVIDUAL';
ALTER TABLE departments ADD COLUMN IF NOT EXISTS default_candidate_interval_minutes INTEGER;
ALTER TABLE departments ADD COLUMN IF NOT EXISTS default_session_duration_minutes INTEGER;
ALTER TABLE departments ADD COLUMN IF NOT EXISTS default_break_minutes INTEGER;

UPDATE departments
SET code = UPPER(REGEXP_REPLACE(name, '[^[:alnum:]]+', '_', 'g'))
WHERE code IS NULL;

UPDATE departments
SET exam_type = CASE
    WHEN LOWER(name) LIKE '%spor%' OR LOWER(name) LIKE '%antren%' OR LOWER(name) LIKE '%egzersiz%' THEN 'TRACK'
    WHEN LOWER(name) LIKE '%resim%' OR LOWER(name) LIKE '%grafik%' OR LOWER(name) LIKE '%seramik%' THEN 'GROUP'
    ELSE 'INDIVIDUAL'
END
WHERE exam_type IS NULL OR exam_type = 'INDIVIDUAL';

UPDATE departments
SET default_candidate_interval_minutes = CASE
        WHEN exam_type = 'INDIVIDUAL' THEN 20
        WHEN exam_type = 'TRACK' THEN 5
        ELSE NULL
    END,
    default_session_duration_minutes = CASE
        WHEN exam_type = 'GROUP' THEN 120
        ELSE NULL
    END,
    default_break_minutes = CASE
        WHEN exam_type = 'INDIVIDUAL' THEN 5
        ELSE 0
    END
WHERE default_candidate_interval_minutes IS NULL
  AND default_session_duration_minutes IS NULL
  AND default_break_minutes IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_departments_code ON departments(code);

CREATE TABLE IF NOT EXISTS classrooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    capacity INTEGER NOT NULL,
    building VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_classroom_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT chk_classroom_capacity CHECK (capacity > 0)
);

CREATE INDEX IF NOT EXISTS idx_classrooms_department ON classrooms(department_id);

CREATE TABLE IF NOT EXISTS jury_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jury_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    available_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    CONSTRAINT fk_jury_availability_jury FOREIGN KEY (jury_id) REFERENCES users(id),
    CONSTRAINT fk_jury_availability_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT chk_jury_availability_time CHECK (end_time > start_time)
);

CREATE INDEX IF NOT EXISTS idx_jury_availability_department_date ON jury_availability(department_id, available_date);
CREATE INDEX IF NOT EXISTS idx_jury_availability_jury_date ON jury_availability(jury_id, available_date);
