ALTER TABLE departments ADD COLUMN IF NOT EXISTS required_primary_jury_count INTEGER NOT NULL DEFAULT 3;
ALTER TABLE departments ADD COLUMN IF NOT EXISTS required_backup_jury_count INTEGER NOT NULL DEFAULT 1;
ALTER TABLE departments ADD COLUMN IF NOT EXISTS jury_self_inactive_deadline_hours INTEGER NOT NULL DEFAULT 24;

ALTER TABLE jury_assignments ADD COLUMN IF NOT EXISTS assignment_role VARCHAR(32) NOT NULL DEFAULT 'PRIMARY';

CREATE TABLE IF NOT EXISTS jury_inactive_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jury_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    inactive_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    reason VARCHAR(255),
    CONSTRAINT fk_jury_inactive_jury FOREIGN KEY (jury_id) REFERENCES users(id),
    CONSTRAINT fk_jury_inactive_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT chk_jury_inactive_time CHECK (
        (start_time IS NULL AND end_time IS NULL)
        OR (start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)
    )
);

CREATE INDEX IF NOT EXISTS idx_jury_inactive_department_date ON jury_inactive_slots(department_id, inactive_date);
CREATE INDEX IF NOT EXISTS idx_jury_inactive_jury_date ON jury_inactive_slots(jury_id, inactive_date);

CREATE TABLE IF NOT EXISTS exam_session_juries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_session_id BIGINT NOT NULL,
    jury_id BIGINT NOT NULL,
    assignment_role VARCHAR(32) NOT NULL,
    replacement BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_exam_session_jury_session FOREIGN KEY (exam_session_id) REFERENCES exam_sessions(id),
    CONSTRAINT fk_exam_session_jury_user FOREIGN KEY (jury_id) REFERENCES users(id),
    CONSTRAINT uk_exam_session_jury UNIQUE (exam_session_id, jury_id)
);

CREATE INDEX IF NOT EXISTS idx_exam_session_juries_session ON exam_session_juries(exam_session_id);
CREATE INDEX IF NOT EXISTS idx_exam_session_juries_jury ON exam_session_juries(jury_id);
